#!/bin/sh
# native/tools/term-stubcheck/run.sh — type-check the app's terminal
# (native/ios/App/Terminal) on Linux against stubs: the renderer stubcheck's
# SwiftUI/UIKit stubs (../swiftui-stubcheck/Stubs) plus Stubs/ here (more
# UIKit, SwiftUI's GeometryReader/KeyPress/@Bindable…, SwiftTerm 1.20's API,
# the few App/Model types it uses), with the real XbinCore and XbinTerm, in
# Swift 6 mode. A pass means "consistent with these stubs" (README.md).
#
#   run.sh [--sendable-bindings] [--sdk-27-1] [build-dir]
#
# --sendable-bindings: Binding(get:set:) closures @Sendable (the strictest
#   reading of the SDK; the terminal's own new code avoids them).
# --sdk-27-1: also compile the XBIN_SDK_27_1 code (the iPhone Duo APIs as
#   reported, stubbed in Stubs/SwiftUITerm.swift).
set -eu
here=$(cd "$(dirname "$0")" && pwd)
repo=$(cd "$here/../../.." && pwd)
strict=0
sdk271=0
while [ $# -gt 0 ]; do
  case "$1" in
    --sendable-bindings) strict=1; shift ;;
    --sdk-27-1) sdk271=1; shift ;;
    *) break ;;
  esac
done
out=${1:-${TMPDIR:-/tmp}/xbin-term-stubcheck}
shared=$repo/native/tools/swiftui-stubcheck/Stubs

mkdir -p "$out/Sources"
rm -rf "$out/Sources/SwiftUI" "$out/Sources/UIKit" "$out/Sources/SwiftTerm" "$out/Sources/TermCheck"
cp -R "$shared/SwiftUI" "$shared/UIKit" "$out/Sources/"
cp "$here/Stubs/UIKitTerm.swift" "$out/Sources/UIKit/"
cp "$here/Stubs/SwiftUITerm.swift" "$out/Sources/SwiftUI/"
# The renderer's UIView/UIResponder are too thin for UIKit code: Stubs/UIKitTerm.swift
# replaces them (NSObject-based, init(frame:)).
python3 - "$out/Sources/UIKit/UIKit.swift" <<'PY'
import re, sys
p = sys.argv[1]
s = open(p).read()
s = s.replace('@MainActor open class UIResponder {}\n', '')
s = re.sub(r'public struct UIEdgeInsets: Sendable, Equatable \{.*?\n\}\n', '', s, flags=re.S)
s = re.sub(r'@MainActor open class UIView: UIResponder \{.*?\n\}\n', '', s, flags=re.S)
s = re.sub(r'extension UIScene: Hashable \{.*?\n\}\n', '', s, flags=re.S)
s = s.replace('public init(frame: CGRect) { super.init(); self.frame = frame }',
              'public override init(frame: CGRect) { super.init(frame: frame) }\n    public required init?(coder: NSCoder) { super.init(coder: coder) }')
s = s.replace('public init(windowScene: UIWindowScene) { super.init() }', 'public init(windowScene: UIWindowScene) { super.init(frame: .zero) }')
s = s.replace('    public var isHidden = true\n', '')
open(p, 'w').write(s)
PY
if [ "$strict" = 1 ]; then
  sed -i.orig 's/public init(get: @escaping () -> Value, set: @escaping (Value) -> Void)/public init(get: @escaping @Sendable () -> Value, set: @escaping @Sendable (Value) -> Void)/' \
    "$out/Sources/SwiftUI/State.swift"
  rm -f "$out/Sources/SwiftUI/State.swift.orig"
fi
mkdir -p "$out/Sources/SwiftTerm" "$out/Sources/TermCheck"
cp "$here/Stubs/SwiftTerm.swift" "$out/Sources/SwiftTerm/"
cp "$here/Stubs/AppStubs.swift" "$out/Sources/TermCheck/"
for f in "$repo"/native/ios/App/Terminal/*.swift; do
  b=$(basename "$f")
  # URLSession's WebSocket API isn't Linux's; Stubs/AppStubs.swift declares its init.
  [ "$b" = WebSocketTransport.swift ] && continue
  # No Objective-C runtime here: @objc goes, #selector(x) becomes a stub Selector("x").
  sed -E -e 's/@objc //g' -e 's/#selector\(([A-Za-z_][A-Za-z0-9_]*)(\([^)]*\))?\)/Selector("\1")/g' "$f" >"$out/Sources/TermCheck/$b"
done

cat >"$out/Package.swift" <<PKG
// swift-tools-version: 6.2
// Generated by native/tools/term-stubcheck/run.sh — do not edit.
import PackageDescription
let package = Package(
    name: "term-stubcheck",
    platforms: [.macOS(.v26)],
    dependencies: [
        .package(path: "$repo/native/ios/Packages/XbinCore"),
        .package(path: "$repo/native/ios/Packages/XbinTerm"),
    ],
    targets: [
        .target(name: "UIKit"),
        .target(name: "SwiftUI", dependencies: ["UIKit"]),
        .target(name: "SwiftTerm", dependencies: ["UIKit"], swiftSettings: [.swiftLanguageMode(.v5)]),
        .target(name: "TermCheck", dependencies: [
            "SwiftUI", "UIKit", "SwiftTerm",
            .product(name: "XbinCore", package: "XbinCore"),
            .product(name: "XbinTerm", package: "XbinTerm"),
        ]),
    ],
    swiftLanguageModes: [.v6]
)
PKG
cd "$out"
if [ "$sdk271" = 1 ]; then swift build -Xswiftc -DXBIN_SDK_27_1; else swift build; fi
