#!/bin/sh
# native/tools/widget-stubcheck/run.sh — type-check the Live Activity code
# on Linux: the widget extension (native/ios/Widgets) and the app's push
# code (native/ios/App/Push) against hand-written stubs of ActivityKit,
# WidgetKit and UserNotifications (Stubs/), the SwiftUI and UIKit stubs of
# ../swiftui-stubcheck, shims of the app types App/Push touches, and the
# real XbinCore and XbinAgent — in Swift 6 mode. Like swiftui-stubcheck: a
# pass means "consistent with the stubs" (our own mistakes caught before a
# CI round trip), not "compiles for iOS".
#
#   run.sh [build-dir]
set -eu
here=$(cd "$(dirname "$0")" && pwd)
repo=$(cd "$here/../../.." && pwd)
ios=$repo/native/ios
out=${1:-${TMPDIR:-/tmp}/xbin-widget-stubcheck}

mkdir -p "$out/Sources"
rm -rf "$out/Sources"/*
cp -R "$repo/native/tools/swiftui-stubcheck/Stubs/SwiftUI" "$repo/native/tools/swiftui-stubcheck/Stubs/UIKit" "$out/Sources/"
cp -R "$here/Stubs/ActivityKit" "$here/Stubs/WidgetKit" "$here/Stubs/UserNotifications" "$out/Sources/"

# The widget extension, with a PushKeyring shim (Shared/Keychain.swift needs Security).
mkdir -p "$out/Sources/WidgetCheck"
(cd "$ios/Widgets" && find . -name '*.swift') | while read -r f; do
  cp "$ios/Widgets/$f" "$out/Sources/WidgetCheck/$(printf '%s' "$f" | sed 's|^\./||; s|/|_|g')"
done
{ echo 'import Foundation'; sed -n '/^struct PushKeyring/,/^}$/p' "$here/Stubs/AppShims/AppShims.swift"; } >"$out/Sources/WidgetCheck/PushKeyringShim.swift"

# The app's push code, with the app-type shims.
mkdir -p "$out/Sources/AppPushCheck"
cp "$ios/App/Push/"*.swift "$ios/Widgets/Shared/"*.swift "$here/Stubs/AppShims/AppShims.swift" "$out/Sources/AppPushCheck/"

cat >"$out/Package.swift" <<PKG
// swift-tools-version: 6.2
// Generated by native/tools/widget-stubcheck/run.sh — do not edit.
import PackageDescription
let package = Package(
    name: "widget-stubcheck",
    platforms: [.macOS(.v26)],
    dependencies: [
        .package(path: "$ios/Packages/XbinCore"),
        .package(path: "$ios/Packages/XbinAgent"),
    ],
    targets: [
        .target(name: "UIKit"),
        .target(name: "SwiftUI", dependencies: ["UIKit"]),
        .target(name: "ActivityKit"),
        .target(name: "WidgetKit", dependencies: ["SwiftUI", "ActivityKit"]),
        .target(name: "UserNotifications", dependencies: ["UIKit"]),
        .target(name: "WidgetCheck", dependencies: [
            "SwiftUI", "WidgetKit", "ActivityKit", .product(name: "XbinAgent", package: "XbinAgent"),
        ]),
        .target(name: "AppPushCheck", dependencies: [
            "UIKit", "ActivityKit", "UserNotifications",
            .product(name: "XbinCore", package: "XbinCore"), .product(name: "XbinAgent", package: "XbinAgent"),
        ]),
    ],
    swiftLanguageModes: [.v6]
)
PKG
cd "$out" && swift build
