//go:build linux && integration

// Run with: go test -tags=integration ./internal/runner/ -run Confined
// Needs user namespaces and an unpacked rootfs (XBIN_TEST_ROOTFS, or the
// repo's .rootfs); skips otherwise.
package runner

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/xbin-dev/xbin/internal/confine"
	"github.com/xbin-dev/xbin/internal/registry"
	"github.com/xbin-dev/xbin/internal/sandbox"
	"github.com/xbin-dev/xbin/internal/util"
)

func TestMain(m *testing.M) {
	if len(os.Args) > 2 && os.Args[1] == sandbox.InitArg {
		sandbox.RunInit(os.Args[2])
	}
	os.Exit(m.Run())
}

// A Go backend builds inside the sandbox with the host toolchain: the
// workspace's go.work resolves through the read-only root bind, the binary
// lands in the tile's build dir, caches are the tile's own — and a hostile
// .git/config (which VCS stamping would run) never runs on the host.
func TestConfinedGoBuild(t *testing.T) {
	fs := os.Getenv("XBIN_TEST_ROOTFS")
	if fs == "" {
		fs, _ = filepath.Abs("../../.rootfs")
	}
	if _, err := os.Stat(filepath.Join(fs, "etc", "os-release")); err != nil || !sandbox.Available() {
		t.Skip("no rootfs or no user namespaces")
	}
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("no go")
	}
	root := t.TempDir()
	tile := filepath.Join(root, "apps", "x")
	write := func(p, s string) {
		t.Helper()
		_ = os.MkdirAll(filepath.Dir(p), 0o755)
		if err := os.WriteFile(p, []byte(s), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write(filepath.Join(tile, "go.mod"), "module example.com/x\n\ngo 1.22\n")
	write(filepath.Join(tile, "backend", "main.go"), "package main\n\nimport \"fmt\"\n\nfunc main() { fmt.Println(\"built in a box\") }\n")
	write(filepath.Join(root, "go.work"), "go 1.22\n\nuse ./apps/x\n")
	write(filepath.Join(root, "data", "vault"), "secret")
	marker := filepath.Join(t.TempDir(), "PWNED")
	if out, err := exec.Command("git", "-C", tile, "init", "-q").CombinedOutput(); err != nil {
		t.Fatalf("git init: %v %s", err, out)
	}
	cfg, _ := os.OpenFile(filepath.Join(tile, ".git", "config"), os.O_APPEND|os.O_WRONLY, 0)
	_, _ = cfg.WriteString("[core]\n\tfsmonitor = \"touch " + marker + "; echo\"\n")
	cfg.Close()

	confine.Configure(fs)
	defer confine.Configure("")
	r := &Runner{Root: root, Isolate: true, Rootfs: fs}
	c := &registry.Component{Path: "apps/x", Dir: tile, Manifest: registry.Manifest{Runtime: "go"}}
	bin, err := r.build(c)
	if err != nil {
		if be, ok := err.(*BuildError); ok {
			t.Fatalf("build: %s", be.Output)
		}
		t.Fatalf("build: %v", err)
	}
	out, err := exec.Command(bin).Output()
	if err != nil || strings.TrimSpace(string(out)) != "built in a box" {
		t.Fatalf("the backend: %q %v", out, err)
	}
	if _, err := os.Stat(marker); err == nil {
		t.Fatal("the tile's .git/config ran on the host")
	}
	for _, d := range []string{"go-build", "mod"} {
		if _, err := os.Stat(filepath.Join(root, ".xbin", "cache", "tile", util.CompKey("apps/x"), d)); err != nil {
			t.Fatalf("the tile's own %s cache: %v", d, err)
		}
	}
	// a compile error comes back as the build's output, like a host build's
	write(filepath.Join(tile, "backend", "main.go"), "package main\n\nfunc main() { undefined() }\n")
	if _, err := r.build(c); err == nil || !strings.Contains(err.(*BuildError).Output, "undefined") {
		t.Fatalf("a broken build: %v", err)
	}
}

// A confined build in a workspace whose go.work xbind generated writes the
// checksums it must add — here of a module the tile's go.mod names with no
// go.sum — to a go.work.sum of the tile's own: the workspace is read-only
// in the build, and every such build used to fail with "go: updating
// go.sum: … read-only file system" (WP-21's live harness run: the agent
// template beside sandbox-terminal broke every Go tile's build). The
// workspace's own go.work.sum seeds the tile's and is never written.
func TestConfinedGoBuildWorkSum(t *testing.T) {
	fs := os.Getenv("XBIN_TEST_ROOTFS")
	if fs == "" {
		fs, _ = filepath.Abs("../../.rootfs")
	}
	if _, err := os.Stat(filepath.Join(fs, "etc", "os-release")); err != nil || !sandbox.Available() {
		t.Skip("no rootfs or no user namespaces")
	}
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("no go")
	}
	root := t.TempDir()
	tile := filepath.Join(root, "apps", "x")
	write := func(p, s string) {
		t.Helper()
		_ = os.MkdirAll(filepath.Dir(p), 0o755)
		if err := os.WriteFile(p, []byte(s), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	// x/sys at xbin's own version: the host's module cache holds it
	write(filepath.Join(tile, "go.mod"), "module example.com/x\n\ngo 1.22\n\nrequire golang.org/x/sys v0.46.0\n")
	write(filepath.Join(tile, "backend", "main.go"), "package main\n\nimport (\n\t\"fmt\"\n\n\t\"golang.org/x/sys/unix\"\n)\n\nfunc main() { fmt.Println(\"pid\", unix.Getpid() > 0) }\n")
	write(filepath.Join(root, "apps", "y", "go.mod"), "module example.com/y\n\ngo 1.22\n")
	gw := "// Code generated by xbind; DO NOT EDIT (remove this line to take ownership).\n\ngo 1.24\n\nuse (\n\t./apps/x\n\t./apps/y\n)\n"
	write(filepath.Join(root, "go.work"), gw)
	write(filepath.Join(root, "go.work.sum"), "example.com/seeded v1.0.0/go.mod h1:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=\n")

	confine.Configure(fs)
	defer confine.Configure("")
	r := &Runner{Root: root, Isolate: true, Rootfs: fs}
	c := &registry.Component{Path: "apps/x", Dir: tile, Manifest: registry.Manifest{Runtime: "go"}}
	bin, err := r.build(c)
	if err != nil {
		if be, ok := err.(*BuildError); ok {
			t.Fatalf("build: %s", be.Output)
		}
		t.Fatalf("build: %v", err)
	}
	if out, err := exec.Command(bin).Output(); err != nil || strings.TrimSpace(string(out)) != "pid true" {
		t.Fatalf("the backend: %q %v", out, err)
	}
	own, err := os.ReadFile(filepath.Join(filepath.Dir(buildGoWork(t, root, "apps/x")), "go.work.sum"))
	if err != nil || !strings.Contains(string(own), "golang.org/x/sys v0.46.0 h1:") || !strings.Contains(string(own), "example.com/seeded") {
		t.Fatalf("the tile's own go.work.sum: %q %v", own, err)
	}
	if ws, _ := os.ReadFile(filepath.Join(root, "go.work.sum")); strings.Contains(string(ws), "x/sys") {
		t.Fatalf("the workspace's go.work.sum was written: %q", ws)
	}
	if cur, _ := os.ReadFile(filepath.Join(root, "go.work")); string(cur) != gw {
		t.Fatalf("the workspace's go.work changed: %q", cur)
	}
}

// covers D166 — F6's race, as it happened: a fresh workspace's generated
// go.work lists no module yet, the new Go tile is registered, and its first
// build — confined, and with isolation off — ran before deps.GoWork listed
// it: "go: no modules were found in the current workspace", sticky until
// the code changed. A build's go.work is its own, made at build time.
func TestFirstBuildBeforeGoWork(t *testing.T) {
	fs := ckRootfs(t)
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("no go")
	}
	for _, isolate := range []bool{true, false} {
		root := t.TempDir()
		w := func(rel, s string) { ckWrite(t, filepath.Join(root, filepath.FromSlash(rel)), s) }
		w("apps/c/xbin.json", `{"runtime":"go"}`)
		w("apps/c/go.mod", "module c\n\ngo 1.22\n")
		w("apps/c/backend/main.go", "package main\n\nimport \"fmt\"\n\nfunc main() { fmt.Println(\"first build\") }\n")
		w("go.work", "// Code generated by xbind; DO NOT EDIT (remove this line to take ownership).\n\ngo 1.24\n\nuse (\n)\n")
		reg, err := registry.Open(root)
		if err != nil {
			t.Fatal(err)
		}
		confine.Configure(fs)
		r := &Runner{Root: root, Isolate: isolate, Rootfs: fs, Reg: reg}
		c, _ := reg.Component("apps/c")
		bin, err := r.build(c)
		confine.Configure("")
		if err != nil {
			if be, ok := err.(*BuildError); ok {
				t.Fatalf("isolate=%v: the first build: %s", isolate, be.Output)
			}
			t.Fatalf("isolate=%v: the first build: %v", isolate, err)
		}
		if out, err := exec.Command(bin).Output(); err != nil || strings.TrimSpace(string(out)) != "first build" {
			t.Fatalf("isolate=%v: the backend: %q %v", isolate, out, err)
		}
	}
}

// buildGoWork is the go.work tile's last work-tree build ran with (D166):
// the one workspace directory under the tile's work/.
func buildGoWork(t *testing.T, root, tile string) string {
	t.Helper()
	m, _ := filepath.Glob(filepath.Join(root, ".xbin", "cache", "tile", util.CompKey(tile), "work", "*", "go.work"))
	if len(m) != 1 {
		t.Fatalf("%s's build workspaces: %q", tile, m)
	}
	return m[0]
}

// xsysPin is golang.org/x/sys as xbin's own go.sum pins it — a version the
// host's module cache holds (xbin builds with it) — and its go.sum lines.
func xsysPin(t *testing.T) (version, sums string) {
	t.Helper()
	b, err := os.ReadFile("../../go.sum")
	if err != nil {
		t.Skip("no go.sum of xbin's:", err)
	}
	for _, l := range strings.Split(string(b), "\n") {
		if f := strings.Fields(l); len(f) == 3 && f[0] == "golang.org/x/sys" && !strings.HasSuffix(f[1], "/go.mod") {
			version = f[1]
		}
	}
	for _, l := range strings.Split(string(b), "\n") {
		if f := strings.Fields(l); len(f) == 3 && f[0] == "golang.org/x/sys" && strings.TrimSuffix(f[1], "/go.mod") == version {
			sums += l + "\n"
		}
	}
	if version == "" {
		t.Skip("xbin's go.sum pins no golang.org/x/sys")
	}
	return version, sums
}

// covers D166 — each Go tile builds with a go.work of its own, not the
// workspace's: under the shared go.work, tile a's go.mod — a replace of
// x/sys and a requirement bump of example.com/dep tied to its own code by a
// version-specific replace — changes what tile b compiles (the control
// build, the go command itself, shows it: b prints a's code), while b's
// confined build compiles b's own dependencies, and its go.work names no
// module of a's. And a tile that builds against other tiles' modules — one
// imported without a require (`lib`, no dot), one required at v0.0.0 —
// builds the moment the registry lists it, before the root go.work does
// (the race: "go: no modules were found in the current workspace").
func TestConfinedGoBuildOwnWorkspace(t *testing.T) {
	fs := ckRootfs(t)
	gobin, err := exec.LookPath("go")
	if err != nil {
		t.Skip("no go")
	}
	sysVer, sysSums := xsysPin(t)
	root := t.TempDir()
	w := func(rel, s string) { ckWrite(t, filepath.Join(root, filepath.FromSlash(rel)), s) }
	// a: steered every Go build of the workspace under the shared go.work
	w("apps/a/xbin.json", `{"runtime":"go"}`)
	w("apps/a/go.mod", "module a\n\ngo 1.22\n\nrequire (\n\tgolang.org/x/sys "+sysVer+"\n\texample.com/dep v1.1.0\n)\n\nreplace golang.org/x/sys => ./evil\n\nreplace example.com/dep v1.1.0 => ./dep\n")
	w("apps/a/a.go", "package a\n\nimport _ \"example.com/dep\"\n")
	w("apps/a/evil/go.mod", "module golang.org/x/sys\n\ngo 1.22\n")
	w("apps/a/evil/unix/unix.go", "package unix\n\nfunc Getpid() int { return -1 }\n")
	w("apps/a/dep/go.mod", "module example.com/dep\n\ngo 1.22\n")
	w("apps/a/dep/dep.go", "package dep\n\nconst Who = \"a's dep v1.1.0\"\n")
	// b: its own dependencies
	w("apps/b/xbin.json", `{"runtime":"go"}`)
	w("apps/b/go.mod", "module b\n\ngo 1.22\n\nrequire (\n\tgolang.org/x/sys "+sysVer+"\n\texample.com/dep v1.0.0\n)\n\nreplace example.com/dep v1.0.0 => ./dep\n")
	w("apps/b/go.sum", sysSums)
	w("apps/b/dep/go.mod", "module example.com/dep\n\ngo 1.22\n")
	w("apps/b/dep/dep.go", "package dep\n\nconst Who = \"b's dep v1.0.0\"\n")
	w("apps/b/backend/main.go", "package main\n\nimport (\n\t\"fmt\"\n\n\t\"example.com/dep\"\n\t\"golang.org/x/sys/unix\"\n)\n\nfunc main() { fmt.Println(dep.Who, unix.Getpid() > 0) }\n")
	// c: new, built against two other tiles' modules
	w("apps/lib/xbin.json", `{}`)
	w("apps/lib/go.mod", "module lib\n\ngo 1.22\n")
	w("apps/lib/greet/greet.go", "package greet\n\nfunc Hi() string { return \"hi from lib\" }\n")
	w("apps/util/xbin.json", `{}`)
	w("apps/util/go.mod", "module example.com/util\n\ngo 1.22\n")
	w("apps/util/util.go", "package util\n\nconst Name = \"util\"\n")
	w("apps/c/xbin.json", `{"runtime":"go"}`)
	w("apps/c/go.mod", "module c\n\ngo 1.22\n\nrequire example.com/util v0.0.0\n")
	w("apps/c/backend/main.go", "package main\n\nimport (\n\t\"fmt\"\n\n\t\"example.com/util\"\n\t\"lib/greet\"\n)\n\nfunc main() { fmt.Println(greet.Hi(), util.Name) }\n")
	// the root go.work as xbind generated it before c: every other module
	gw := "// Code generated by xbind; DO NOT EDIT (remove this line to take ownership).\n\ngo 1.24\n\nuse (\n\t./apps/a\n\t./apps/b\n\t./apps/lib\n\t./apps/util\n)\n"
	w("go.work", gw)

	// the control: the go command itself, with the shared go.work, compiles
	// a's code into b — the hole this closes
	ctl := filepath.Join(t.TempDir(), "ctl")
	cmd := exec.Command(gobin, "build", "-o", ctl, "./backend")
	cmd.Dir = filepath.Join(root, "apps/b")
	cmd.Env = append(os.Environ(), "GOWORK="+filepath.Join(root, "go.work"), "GOPROXY=off", "GOFLAGS=", "CGO_ENABLED=0")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("the control build: %v\n%s", err, out)
	}
	if out, _ := exec.Command(ctl).Output(); strings.TrimSpace(string(out)) != "a's dep v1.1.0 false" {
		t.Fatalf("the control: b built with the shared go.work printed %q, want a's code (the premise)", out)
	}

	reg, err := registry.Open(root)
	if err != nil {
		t.Fatal(err)
	}
	confine.Configure(fs)
	defer confine.Configure("")
	r := &Runner{Root: root, Isolate: true, Rootfs: fs, Reg: reg}
	build := func(tile, want string) {
		t.Helper()
		c, ok := reg.Component(tile)
		if !ok {
			t.Fatalf("%s isn't registered", tile)
		}
		bin, err := r.build(c)
		if err != nil {
			if be, ok := err.(*BuildError); ok {
				t.Fatalf("build %s: %s", tile, be.Output)
			}
			t.Fatalf("build %s: %v", tile, err)
		}
		if out, err := exec.Command(bin).Output(); err != nil || strings.TrimSpace(string(out)) != want {
			t.Fatalf("%s's backend: %q %v, want %q", tile, out, err, want)
		}
	}
	build("apps/b", "b's dep v1.0.0 true")
	if b, _ := os.ReadFile(buildGoWork(t, root, "apps/b")); strings.Contains(string(b), "apps/a") || !strings.Contains(string(b), filepath.Join(root, "apps/b")) {
		t.Errorf("b's build workspace:\n%s", b)
	}
	build("apps/c", "hi from lib util")
	b, _ := os.ReadFile(buildGoWork(t, root, "apps/c"))
	for _, m := range []string{"apps/c", "apps/lib", "apps/util"} {
		if !strings.Contains(string(b), "\t"+filepath.Join(root, m)+"\n") {
			t.Errorf("c's build workspace doesn't use %s:\n%s", m, b)
		}
	}
	if strings.Contains(string(b), "apps/a") || strings.Contains(string(b), "apps/b\n") {
		t.Errorf("c's build workspace uses a module it doesn't reach:\n%s", b)
	}
	if cur, _ := os.ReadFile(filepath.Join(root, "go.work")); string(cur) != gw {
		t.Fatalf("the workspace's go.work changed: %q", cur)
	}

	// a's own build compiles its own choices, as before
	w("apps/a/backend/main.go", "package main\n\nimport (\n\t\"fmt\"\n\n\t\"example.com/dep\"\n\t\"golang.org/x/sys/unix\"\n)\n\nfunc main() { fmt.Println(dep.Who, unix.Getpid() > 0) }\n")
	build("apps/a", "a's dep v1.1.0 false")

	// a tile relying on another tile's requirement: the build says what to add
	w("apps/d/xbin.json", `{"runtime":"go"}`)
	w("apps/d/go.mod", "module d\n\ngo 1.22\n")
	w("apps/d/backend/main.go", "package main\n\nimport (\n\t\"fmt\"\n\n\t\"golang.org/x/sys/unix\"\n)\n\nfunc main() { fmt.Println(unix.Getpid() > 0) }\n")
	if err := reg.Rescan(); err != nil {
		t.Fatal(err)
	}
	d, _ := reg.Component("apps/d")
	_, err = r.build(d)
	be, ok := err.(*BuildError)
	if !ok || !strings.Contains(be.Output, "no required module provides package golang.org/x/sys/unix") || !strings.Contains(be.Output, "add `require golang.org/x/sys "+sysVer+"` to apps/d's go.mod") {
		t.Fatalf("a missing requirement: %v", err)
	}
}
