package runner

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// tileGoWork writes the tile's go.work (and seeds its go.work.sum) in a dir
// every build of the tile has read-write: a symlink a build left there is
// replaced, never written through — xbind writes nothing through a
// sandbox-written path (D78).
func TestTileGoWorkNoFollow(t *testing.T) {
	root := t.TempDir()
	gen := "// Code generated by xbind; DO NOT EDIT (remove this line to take ownership).\n\ngo 1.24\n\nuse (\n\t./apps/x\n)\n"
	if err := os.WriteFile(filepath.Join(root, "go.work"), []byte(gen), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "go.work.sum"), []byte("seed\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	r := &Runner{Root: root}

	// a fresh dir: go.work with absolute paths, go.work.sum seeded
	fresh := filepath.Join(root, ".xbin", "cache", "tile", "k1", "work")
	gw, err := r.tileGoWork(fresh)
	if err != nil || gw != filepath.Join(fresh, "go.work") {
		t.Fatalf("tileGoWork: %q %v", gw, err)
	}
	if b, _ := os.ReadFile(gw); !strings.Contains(string(b), "\t"+filepath.Join(root, "apps", "x")+"\n") {
		t.Errorf("the tile's go.work:\n%s", b)
	}
	if b, _ := os.ReadFile(gw + ".sum"); string(b) != "seed\n" {
		t.Errorf("the tile's go.work.sum: %q", b)
	}

	// a dir a build planted links in
	victim := filepath.Join(t.TempDir(), "victim")
	if err := os.WriteFile(victim, []byte("precious\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	dir := filepath.Join(root, ".xbin", "cache", "tile", "k2", "work")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(victim, filepath.Join(dir, "go.work")); err != nil {
		t.Fatal(err)
	}
	if gw, err = r.tileGoWork(dir); err != nil {
		t.Fatal(err)
	}
	if b, _ := os.ReadFile(victim); string(b) != "precious\n" {
		t.Fatalf("written through the build's symlink: %q", b)
	}
	if fi, err := os.Lstat(gw); err != nil || !fi.Mode().IsRegular() {
		t.Fatalf("the tile's go.work isn't a regular file: %v %v", fi, err)
	}

	// a dangling link as go.work.sum is left alone: nothing written through it
	dir3 := filepath.Join(root, ".xbin", "cache", "tile", "k3", "work")
	_ = os.MkdirAll(dir3, 0o755)
	target := filepath.Join(t.TempDir(), "made")
	if err := os.Symlink(target, filepath.Join(dir3, "go.work.sum")); err != nil {
		t.Fatal(err)
	}
	if _, err := r.tileGoWork(dir3); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Lstat(target); !os.IsNotExist(err) {
		t.Fatalf("the seed was written through a link: %v", err)
	}

	// a hand-managed go.work: used as it is
	if err := os.WriteFile(filepath.Join(root, "go.work"), []byte("go 1.24\n\nuse ./apps/x\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if gw, err := r.tileGoWork(filepath.Join(root, "k4")); gw != "" || err != nil {
		t.Fatalf("a hand-managed go.work: %q %v", gw, err)
	}
}
