#!/bin/sh
# native/tools/uitest-stubcheck/run.sh — type-check native/ios/UITests on
# Linux, in Swift 6 mode, against hand-written stubs of the XCTest/XCUITest
# API (Stubs/XCTest.swift; the UI classes @MainActor as the iOS SDK declares
# them). A pass means "consistent with these stubs": syntax, types, optionals
# and actor isolation — not that it compiles for iOS; the ios.yml app job
# does that (build-for-testing). README.md says more.
#
#   run.sh [build-dir]
set -eu
here=$(cd "$(dirname "$0")" && pwd)
repo=$(cd "$here/../../.." && pwd)
out=${1:-${TMPDIR:-/tmp}/xbin-uitest-stubcheck}
command -v swift >/dev/null 2>&1 || { echo "uitest-stubcheck: no swift on PATH — skipped"; exit 0; }

rm -rf "$out/Sources"
mkdir -p "$out/Sources/XCTestStubs" "$out/Sources/UITestsCheck"
cp "$here/Stubs/XCTest.swift" "$out/Sources/XCTestStubs/"
for f in "$repo"/native/ios/UITests/*.swift; do
  sed -e 's/^import XCTest$/import XCTestStubs/' -e 's/NSPredicate(/StubPredicate(/g' "$f" >"$out/Sources/UITestsCheck/$(basename "$f")"
done
cat >"$out/Package.swift" <<'EOF'
// swift-tools-version: 6.0
// Generated by native/tools/uitest-stubcheck/run.sh — do not edit.
import PackageDescription
let package = Package(
    name: "uitest-stubcheck",
    targets: [
        .target(name: "XCTestStubs"),
        .target(name: "UITestsCheck", dependencies: ["XCTestStubs"]),
    ],
    swiftLanguageModes: [.v6]
)
EOF
cd "$out"
if ! swift build >build.log 2>&1; then
  grep -E 'error:|warning:' build.log | sed 's|^.*/Sources/UITestsCheck/|native/ios/UITests/|' | sort -u
  echo "uitest-stubcheck: FAILED ($out/build.log)"
  exit 1
fi
grep -E 'warning:' build.log | sed 's|^.*/Sources/UITestsCheck/|native/ios/UITests/|' | sort -u || true
echo "uitest-stubcheck: ok ($(ls "$repo"/native/ios/UITests/*.swift | wc -l | tr -d ' ') files, Swift 6)"
