#!/usr/bin/env node
// native/tools/icons.mjs — regenerate web/xb/render-icons.js, the reference
// renderer's icon subset, from a Lucide icon set (ISC; https://lucide.dev).
// The vocabulary's icon names (web/xb/vocab.js ICONS → SF Symbols on iOS)
// map to Lucide icons here; the renderer adds a few of its own (UI chrome).
//
//   node native/tools/icons.mjs <lucide-react or lucide package dir> > web/xb/render-icons.js
//
// Any Lucide distribution with dist/esm/icons/<name>.js (lucide-react,
// lucide) works; the version is read from its package.json.
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { ICONS } from '../../web/xb/vocab.js';

const dir = process.argv[2];
if (!dir) { console.error('usage: node native/tools/icons.mjs <lucide package dir>'); process.exit(2); }
const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));

// vocabulary name → Lucide icon
const MAP = {
  plus: 'plus', minus: 'minus', check: 'check', xmark: 'x',
  copy: 'copy', share: 'share', refresh: 'rotate-cw', gear: 'settings',
  terminal: 'square-terminal', box: 'package', key: 'key-round', lock: 'lock',
  unlock: 'lock-open', globe: 'globe', shield: 'shield-check', bolt: 'zap',
  clock: 'clock', chart: 'chart-line', link: 'link', paperclip: 'paperclip',
  send: 'circle-arrow-up', stop: 'circle-stop', play: 'play', pause: 'pause',
  sparkles: 'sparkles', wrench: 'wrench', warning: 'triangle-alert', trash: 'trash-2',
  list: 'list', ellipsis: 'ellipsis', search: 'search', filter: 'list-filter',
  pencil: 'pencil', folder: 'folder', file: 'file', doc: 'file-text',
  photo: 'image', bell: 'bell', person: 'user', people: 'users',
  star: 'star', heart: 'heart', pin: 'pin', archive: 'archive',
  tag: 'tag', calendar: 'calendar', mail: 'mail', chat: 'message-circle',
  info: 'info', question: 'circle-help', error: 'octagon-x', home: 'house',
  download: 'circle-arrow-down', upload: 'circle-arrow-up', cloud: 'cloud', server: 'server',
  database: 'database', cpu: 'cpu', network: 'network', code: 'code',
  branch: 'git-branch', eye: 'eye', 'eye-slash': 'eye-off', external: 'square-arrow-out-up-right',
  back: 'chevron-left', forward: 'chevron-right', expand: 'chevron-down', collapse: 'chevron-up',
  power: 'power', sun: 'sun', moon: 'moon', agent: 'user-round-check',
};
// the renderer's own chrome (not tile-nameable)
const UI = {
  'ui-updown': 'chevrons-up-down', 'ui-circle': 'circle', 'ui-circle-check': 'circle-check',
  'ui-circle-dot': 'circle-dot', 'ui-arrow-up': 'arrow-up', 'ui-square': 'square',
  'ui-alert': 'circle-alert', 'ui-unknown': 'circle-dashed', 'ui-circle-x': 'circle-x',
  'ui-ban': 'ban', 'ui-expand-full': 'maximize-2', 'ui-file-plus': 'file-plus', 'ui-file-minus': 'file-minus',
  'ui-file-diff': 'file-diff',
};

const missing = Object.keys(ICONS).filter((n) => !MAP[n]);
if (missing.length) { console.error(`no Lucide mapping for: ${missing.join(', ')}`); process.exit(1); }

const attr = (s) => String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
function inner(name) {
  const src = readFileSync(join(dir, 'dist/esm/icons', `${name}.js`), 'utf8');
  const alias = src.match(/export \{ default \} from '\.\/([a-z0-9-]+)\.js'/);
  if (alias) return inner(alias[1]); // a renamed icon's old name
  const m = src.match(/const __iconNode = (\[[\s\S]*?\]);\n/);
  if (!m) throw new Error(`${name}: no __iconNode`);
  const nodes = Function(`return ${m[1]}`)();
  return nodes.map(([tag, attrs]) => `<${tag} ${Object.entries(attrs).filter(([k]) => k !== 'key')
    .map(([k, v]) => `${k}="${attr(v)}"`).join(' ')}/>`).join('');
}

const out = [];
out.push(`/**
 * xb/render-icons.js — the reference renderer's icons: the native
 * vocabulary's curated names (xb/vocab.js ICONS; SF Symbols on iOS) drawn
 * with a subset of Lucide ${pkg.version}. GENERATED by native/tools/icons.mjs —
 * edit the mapping there, not this file.
 *
 * Lucide — ISC License
 * Copyright (c) for portions of Lucide are held by Cole Bemis 2013-2022 as
 * part of Feather (MIT). All other copyright (c) for Lucide are held by
 * Lucide Contributors 2022.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

// name → the inner markup of a 24×24, stroke-drawn (currentColor) SVG
export const ICON_SVG = {`);
for (const [n, l] of [...Object.entries(MAP), ...Object.entries(UI)]) out.push(`  ${JSON.stringify(n)}: ${JSON.stringify(inner(l))},`);
out.push('};\n');
process.stdout.write(out.join('\n'));
