import Foundation
import Testing
@testable import XbinAgent

/// A fixture file from Fixtures/ (captured by internal/term/agent_capture_test.go,
/// or js-parity.json generated by native/tools/agent-parity.mjs).
func fixture(_ name: String) throws -> JSONValue {
    let url = try #require(Bundle.module.resourceURL).appendingPathComponent("Fixtures/\(name).json")
    return try JSONValue.parse(Data(contentsOf: url))
}

/// A captured session's events.
func events(_ name: String) throws -> [AgentEvent] {
    try #require(fixture(name)["events"]?.list(AgentEvent.self))
}

func ev(_ seq: UInt64, _ type: String, _ data: JSONValue, ts: Int64 = 0) -> AgentEvent {
    AgentEvent(seq: seq, ts: ts == 0 ? Int64(seq) * 100 : ts, type: type, data: data)
}

func j(_ s: String) -> JSONValue { try! JSONValue.parse(s) }

extension JSONValue {
    /// Optional → JSON (nil → null), for building expected summaries.
    static func of(_ s: String?) -> JSONValue { s.map { .string($0) } ?? .null }
    static func of(_ n: Int?) -> JSONValue { n.map { .number(Double($0)) } ?? .null }
}

/// The transcript as the parity script summarizes the web's blocks.
func summarize(_ it: TranscriptItem) -> JSONValue {
    switch it {
    case .message(let m):
        var o: JSONValue = ["kind": "msg", "role": .string(m.role.rawValue), "text": .string(m.text), "mid": .string(m.messageId)]
        if !m.files.isEmpty, case .object(var obj) = o {
            obj["files"] = .array(m.files.map { .string($0.name) })
            o = .object(obj)
        }
        return o
    case .thought(let t):
        return ["kind": "thought", "text": .string(t.text), "done": .bool(t.done), "ms": .number(Double(t.endedAt - t.startedAt))]
    case .tool(let t):
        return ["kind": "tool", "id": .string(t.toolCallId), "title": .string(t.title), "tk": .string(t.kind.rawValue), "status": .string(t.status.rawValue),
                "name": .string(t.name), "label": .string(t.label), "parent": .string(t.parent), "subagent": .bool(t.isSubagent),
                "output": .string(t.output), "exitCode": .of(t.exitCode), "headline": .string(t.headline), "command": .string(t.command),
                "plan": .bool(t.isPlanApproval), "files": t.files.map { .array($0.changes.map { .string($0.path) }) } ?? .null,
                "children": t.isSubagent ? .array(t.children.map(summarize)) : .null]
    case .plan(let p):
        return ["kind": "plan", "entries": .array(p.entries.map { .string($0.content + ":" + $0.status.rawValue) })]
    case .permission(let c):
        return ["kind": "perm", "pid": .string(c.pid), "by": .of(c.resolution?.by.raw), "optionId": .of(c.resolution?.optionId), "plan": .bool(c.isPlanApproval)]
    case .question(let q):
        return ["kind": "ask", "eid": .string(q.eid), "action": .of(q.resolution?.action.rawValue), "by": .of(q.resolution?.by.raw),
                "fields": .array(q.fields.map { .string($0.key) })]
    case .changes(let c):
        return ["kind": "changes", "turn": .of(c.turn), "files": .array(c.files.changes.map { .string($0.path) })]
    case .turnEnd(let d):
        return ["kind": "turn", "turn": .of(d.turn), "stopReason": .string(d.stopReason.rawValue), "error": .of(d.error)]
    case .gap:
        return ["kind": "gap"]
    }
}
