#!/bin/sh
# native/tools/swiftui-stubcheck/run.sh — type-check XbinRenderer's SwiftUI
# sources on Linux against hand-written stubs of the SDK API they use
# (Stubs/). A pass means "consistent with these stubs": it catches our own
# mistakes (wrong model API, optionals, closure types, actor isolation) before
# a CI round trip; it is NOT a substitute for the Apple CI (README.md).
#
#   run.sh [--sendable-bindings] [build-dir]
#
# --sendable-bindings declares Binding(get:set:)'s closures @Sendable, the
# strictest reading of the SDK: the renderer must type-check both ways.
set -eu
here=$(cd "$(dirname "$0")" && pwd)
repo=$(cd "$here/../../.." && pwd)
strict=0
if [ "${1:-}" = "--sendable-bindings" ]; then strict=1; shift; fi
out=${1:-${TMPDIR:-/tmp}/xbin-swiftui-stubcheck}
pkg=$repo/native/ios/Packages/XbinRenderer

mkdir -p "$out/Sources"
rm -rf "$out/Sources/SwiftUI" "$out/Sources/UIKit" "$out/Sources/Charts" "$out/Sources/XbinRendererModel" "$out/Sources/XbinRendererCheck"
cp -R "$here/Stubs/SwiftUI" "$here/Stubs/UIKit" "$here/Stubs/Charts" "$out/Sources/"
cp -R "$pkg/Sources/XbinRendererModel" "$out/Sources/"
mkdir -p "$out/Sources/XbinRendererCheck"
if [ "$strict" = 1 ]; then
  sed -i.orig 's/public init(get: @escaping () -> Value, set: @escaping (Value) -> Void)/public init(get: @escaping @Sendable () -> Value, set: @escaping @Sendable (Value) -> Void)/' \
    "$out/Sources/SwiftUI/State.swift"
  rm -f "$out/Sources/SwiftUI/State.swift.orig"
fi

# The views: guards and #Preview macros dropped (no macros here).
(cd "$pkg/Sources/XbinRenderer" && find . -name '*.swift' ! -name Exports.swift) | while read -r f; do
  name=$(printf '%s' "$f" | sed 's|^\./||; s|/|_|g')
  sed -e '/^#if canImport(UIKit)$/d' -e '/^#endif$/d' -e '/^#Preview/,/^}$/d' \
    "$pkg/Sources/XbinRenderer/$f" >"$out/Sources/XbinRendererCheck/$name"
done
# The snapshot tests, as plain functions (no Testing module here).
sed -e '/^#if canImport(UIKit)$/d' -e '/^#endif$/d' -e 's/^import Testing$//' -e 's/^import XbinRenderer$//' \
  -e 's/^@Suite struct/struct/' -e 's/^    @Test func/    func/' \
  -e 's/try #require(\(.*\), "native\/fixtures not found")/\1!/' -e 's/#expect(/check(/' \
  "$pkg/Tests/XbinRendererTests/SnapshotTests.swift" >"$out/Sources/XbinRendererCheck/SnapshotTests.swift"
printf 'func check(_ c: Bool, _ m: @autoclosure () -> String = "") {}\n' >>"$out/Sources/XbinRendererCheck/SnapshotTests.swift"

cat >"$out/Package.swift" <<EOF
// swift-tools-version: 6.2
// Generated by native/tools/swiftui-stubcheck/run.sh — do not edit.
import PackageDescription
let package = Package(
    name: "stubcheck",
    platforms: [.macOS(.v26)],
    dependencies: [.package(path: "$repo/native/ios/Packages/XbinCore")],
    targets: [
        .target(name: "UIKit"),
        .target(name: "SwiftUI", dependencies: ["UIKit"]),
        .target(name: "Charts", dependencies: ["SwiftUI"]),
        .target(name: "XbinRendererModel", dependencies: [.product(name: "XbinCore", package: "XbinCore")]),
        .target(name: "XbinRendererCheck", dependencies: [
            "SwiftUI", "UIKit", "Charts", "XbinRendererModel", .product(name: "XbinCore", package: "XbinCore"),
        ]),
    ]
)
EOF
cd "$out" && swift build
# …and the snapshot tests as the hosted XbinSnapshotTests compile them.
swift build -Xswiftc -DXBIN_SNAPSHOT_HOST
