package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// cmdDoctor checks the workspace for the problems that actually happen:
// manifest errors, dangling deps, missing API.md on exposing components,
// go.work drift, inotify limits, missing toolchains.
func cmdDoctor() error {
	problems := 0
	warn := func(f string, args ...any) {
		problems++
		fmt.Printf("  ✗ "+f+"\n", args...)
	}
	ok := func(f string, args ...any) { fmt.Printf("  ✓ "+f+"\n", args...) }

	ws := workspaceRoot()
	if ws == "" {
		return fmt.Errorf("not inside a buxon workspace (no buxon.json + .buxon found upward)")
	}
	fmt.Println("workspace:", ws)

	comps, err := components()
	if err != nil {
		warn("buxond unreachable: %v (is it running? is BUXON_URL/BUXON_TOKEN set?)", err)
		comps = nil
	} else {
		ok("buxond reachable, %d components", len(comps))
	}

	byPath := map[string]bool{}
	for _, c := range comps {
		byPath[c.Path] = true
	}
	for _, c := range comps {
		if c.ManifestErr != "" {
			warn("%s: buxon.json: %s", c.Path, c.ManifestErr)
		}
		for _, d := range c.Deps {
			if !byPath[d] {
				warn("%s: dep %q does not exist", c.Path, d)
			}
		}
		if len(c.Roles) > 0 {
			if _, err := os.Stat(filepath.Join(ws, filepath.FromSlash(c.Path), "API.md")); err != nil {
				warn("%s exposes roles but has no API.md (bx new scaffolds one; /docs/elements.md)", c.Path)
			}
			for role, desc := range c.Roles {
				if strings.TrimSpace(desc) == "" {
					warn("%s: role %q has no description", c.Path, role)
				}
			}
		}
	}

	// go.work ownership.
	if b, err := os.ReadFile(filepath.Join(ws, "go.work")); err == nil {
		if strings.Contains(string(b), "Code generated by buxond") {
			ok("go.work is buxond-managed")
		} else {
			fmt.Println("  · go.work is hand-managed (buxond will not touch it)")
		}
	}

	// inotify budget (the #1 support issue per plans/deployment.md).
	if b, err := os.ReadFile("/proc/sys/fs/inotify/max_user_watches"); err == nil {
		n, _ := strconv.Atoi(strings.TrimSpace(string(b)))
		if n < 65536 {
			warn("fs.inotify.max_user_watches=%d is low; set it to 524288 on the host (see /docs/getting-started.md)", n)
		} else {
			ok("inotify watch budget: %d", n)
		}
	}

	// Toolchains for runtimes in use.
	needs := map[string]string{}
	for _, c := range comps {
		switch c.Runtime {
		case "go":
			needs["go"] = c.Path
		case "node":
			needs["node"] = c.Path
		case "python":
			needs["python3"] = c.Path
		}
	}
	for bin, user := range needs {
		if _, err := lookPath(bin); err != nil {
			warn("%s not in PATH (needed by %s)", bin, user)
		}
	}

	if problems == 0 {
		fmt.Println("all good")
		return nil
	}
	return fmt.Errorf("%d problem(s)", problems)
}

func lookPath(bin string) (string, error) {
	for _, dir := range strings.Split(os.Getenv("PATH"), ":") {
		p := filepath.Join(dir, bin)
		if fi, err := os.Stat(p); err == nil && fi.Mode()&0o111 != 0 {
			return p, nil
		}
	}
	return "", fmt.Errorf("not found")
}
