package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// cmdDoctor checks the workspace for the problems that actually happen:
// manifest errors, dangling deps, missing API.md on exposing components,
// go.work drift, inotify limits, missing toolchains.
func cmdDoctor() error {
	problems := 0
	warn := func(f string, args ...any) {
		problems++
		fmt.Printf("  ✗ "+f+"\n", args...)
	}
	ok := func(f string, args ...any) { fmt.Printf("  ✓ "+f+"\n", args...) }

	ws := workspaceRoot()
	if ws == "" {
		return fmt.Errorf("not inside a xbin workspace (no xbin.json + .xbin found upward)")
	}
	fmt.Println("workspace:", ws)

	comps, err := components()
	if err != nil {
		warn("xbind unreachable: %v (is it running? is XBIN_URL/XBIN_TOKEN set?)", err)
		comps = nil
	} else {
		ok("xbind reachable, %d components", len(comps))
	}

	byPath := map[string]bool{}
	for _, c := range comps {
		byPath[c.Path] = true
	}
	for _, c := range comps {
		if c.ManifestErr != "" {
			warn("%s: xbin.json: %s", c.Path, c.ManifestErr)
		}
		for _, d := range c.Deps {
			if !byPath[d] {
				warn("%s: dep %q does not exist", c.Path, d)
			}
		}
		if len(c.Roles) > 0 {
			if _, err := os.Stat(filepath.Join(ws, filepath.FromSlash(c.Path), "API.md")); err != nil {
				warn("%s exposes roles but has no API.md (bx new scaffolds one; /docs/elements.md)", c.Path)
			}
			for role, desc := range c.Roles {
				if strings.TrimSpace(desc) == "" {
					warn("%s: role %q has no description", c.Path, role)
				}
			}
		}
	}

	// Ownership/org sanity (plans/ownership.md D24-D33). Best-effort: needs
	// admin credentials; silently skipped otherwise.
	if comps != nil {
		have := map[string]bool{}
		for _, c := range comps {
			have[c.Path] = true
		}
		matches := func(pat string) bool {
			for p := range have {
				if matchesTilePat(pat, p) {
					return true
				}
			}
			return false
		}
		// Owner entries pointing at paths with no component are orphans (a
		// moved/deleted tile) — clear or re-assign with bx owner.
		var mx struct {
			Owners map[string]string `json:"owners"`
		}
		if err := apiJSON("GET", "/api/xbin/access-matrix", nil, &mx); err == nil {
			for p, o := range mx.Owners {
				if !have[p] {
					warn("owner entry %q -> %s has no component (moved or deleted) — clear or re-assign with bx owner", p, o)
				}
			}
		}
		// Org shape: admin-less orgs are manageable only by ws-admins;
		// member-less orgs are usually leftovers. Allowance entries that fail
		// the grammar (hand-edited users.json) can never match an approval.
		var ov struct {
			Orgs []struct {
				ID            string            `json:"id"`
				Members       []map[string]any  `json:"members"`
				ResolvedAllow []string          `json:"resolvedAllow"`
				Tiles         map[string]string `json:"tiles"`
			} `json:"orgs"`
		}
		if err := apiJSON("GET", "/api/xbin/orgs", nil, &ov); err == nil {
			for _, o := range ov.Orgs {
				if len(o.Members) == 0 {
					warn("org %q has no members — leftover? (bx org rm, or add members)", o.ID)
				} else {
					hasAdmin := false
					for _, m := range o.Members {
						if a, _ := m["admin"].(bool); a {
							hasAdmin = true
						}
					}
					if !hasAdmin {
						warn("org %q has no org admin — only workspace admins can manage it (bx org member %s <user> --admin)", o.ID, o.ID)
					}
				}
				for _, e := range o.ResolvedAllow {
					if msg := allowEntryProblem(e); msg != "" {
						warn("org %q allowance %q: %s (hand-edited? it can never match an approval)", o.ID, e, msg)
					}
				}
				for pat := range o.Tiles {
					if !matches(pat) {
						warn("org %q share %q matches no component", o.ID, pat)
					}
				}
			}
		}
		// defaultTiles patterns that match nothing grant nothing.
		var df struct {
			DefaultTiles map[string]string `json:"defaultTiles"`
		}
		if err := apiJSON("GET", "/api/xbin/defaults", nil, &df); err == nil {
			for pat := range df.DefaultTiles {
				if !matches(pat) {
					warn("defaultTiles pattern %q matches no component", pat)
				}
			}
		}
	}

	// go.work ownership.
	if b, err := os.ReadFile(filepath.Join(ws, "go.work")); err == nil {
		if strings.Contains(string(b), "Code generated by xbind") {
			ok("go.work is xbind-managed")
		} else {
			fmt.Println("  · go.work is hand-managed (xbind will not touch it)")
		}
	}

	// Sandbox uid mapping: a terminal reads its own /proc/self/uid_map. A single
	// mapped range of size 1 (e.g. "0 999 1") is single-uid mode, where apt/dpkg
	// can't chown to the system users their post-install scripts create (chown →
	// "Invalid argument"), so packages like systemd/dbus fail to configure. A
	// delegated sub-id range maps a second, wide row and fixes it. Only meaningful
	// inside a sandboxed terminal (the file is absent/other otherwise).
	if b, err := os.ReadFile("/proc/self/uid_map"); err == nil {
		if singleUIDMap(string(b)) {
			warn("sandbox uid mapping is SINGLE-UID: apt/dpkg installs that create system users (systemd, dbus, …) will fail with chown \"Invalid argument\". Delegate a sub-id range to the xbind user (/etc/subuid + /etc/subgid) and install the uidmap package on the host, then restart xbind (deploy/install.sh does this).")
		} else {
			ok("sandbox uid mapping: full sub-id range")
		}
	}

	// inotify budget (the #1 support issue per plans/deployment.md).
	if b, err := os.ReadFile("/proc/sys/fs/inotify/max_user_watches"); err == nil {
		n, _ := strconv.Atoi(strings.TrimSpace(string(b)))
		if n < 65536 {
			warn("fs.inotify.max_user_watches=%d is low; set it to 524288 on the host (see /docs/getting-started.md)", n)
		} else {
			ok("inotify watch budget: %d", n)
		}
	}

	// Toolchains for runtimes in use.
	needs := map[string]string{}
	for _, c := range comps {
		switch c.Runtime {
		case "go":
			needs["go"] = c.Path
		case "node":
			needs["node"] = c.Path
		case "python":
			needs["python3"] = c.Path
		}
	}
	for bin, user := range needs {
		if _, err := lookPath(bin); err != nil {
			warn("%s not in PATH (needed by %s)", bin, user)
		}
	}

	if problems == 0 {
		fmt.Println("all good")
		return nil
	}
	return fmt.Errorf("%d problem(s)", problems)
}

// singleUIDMap reports whether a /proc/self/uid_map maps only container-root
// (one non-empty row of "<inside> <outside> <count>" with count 1, and no wider
// row). Range mode adds a second row mapping a large count. Empty/odd → not
// flagged (only the clear single-uid case warns).
func singleUIDMap(s string) bool {
	rows := 0
	for _, line := range strings.Split(s, "\n") {
		f := strings.Fields(line)
		if len(f) != 3 {
			continue
		}
		rows++
		if n, err := strconv.Atoi(f[2]); err == nil && n > 1 {
			return false // a wide mapping exists → range mode
		}
	}
	return rows == 1
}

// matchesTilePat mirrors the server's tile-pattern semantics (exact, `*`,
// `prefix/*`, single mid-string glob) for doctor's dead-pattern checks.
func matchesTilePat(pat, path string) bool {
	if pat == "*" || pat == path {
		return true
	}
	if strings.HasSuffix(pat, "/*") {
		prefix := strings.TrimSuffix(pat, "/*")
		return path == prefix || strings.HasPrefix(path, prefix+"/")
	}
	if i := strings.IndexByte(pat, '*'); i >= 0 {
		pre, suf := pat[:i], pat[i+1:]
		return len(path) >= len(pre)+len(suf) && strings.HasPrefix(path, pre) && strings.HasSuffix(path, suf)
	}
	return false
}

// allowEntryProblem is an ADVISORY mirror of the server-side allowance
// grammar (internal/users parseAllowEntry) for doctor: the API refuses bad
// entries at write time, so anything caught here was hand-edited into
// users.json. "" = looks fine.
func allowEntryProblem(e string) string {
	e = strings.TrimSpace(e)
	if e == "" {
		return "empty entry"
	}
	if e == "xbin" || strings.HasPrefix(e, "xbin:") || strings.HasPrefix(e, "cap:xbin") {
		return "the xbin capability family is never delegable"
	}
	class, rest, okCut := strings.Cut(e, ":")
	if !okCut || rest == "" {
		return "not <class>:<value>"
	}
	switch class {
	case "res", "gpu", "cap", "tile", "iface":
		return ""
	case "net":
		if rest == "internet" || rest == "host" ||
			strings.HasPrefix(rest, "lan:") || strings.HasPrefix(rest, "provider:") {
			return ""
		}
		return "net entries are net:internet, net:host, net:lan:<glob> or net:provider:<tile-glob>"
	case "ingress":
		kind, val, _ := strings.Cut(rest, ":")
		if (kind == "host" || kind == "zone" || kind == "listen") && val != "" {
			return ""
		}
		return "ingress entries are ingress:host:/zone:/listen:<value>"
	}
	return "unknown class (res/gpu/cap/net/iface/ingress/tile)"
}

func lookPath(bin string) (string, error) {
	for _, dir := range strings.Split(os.Getenv("PATH"), ":") {
		p := filepath.Join(dir, bin)
		if fi, err := os.Stat(p); err == nil && fi.Mode()&0o111 != 0 {
			return p, nil
		}
	}
	return "", fmt.Errorf("not found")
}
