package scaffold

const indexTpl = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>%[1]s</title>
  <link rel="stylesheet" href="/vendor/theme.css">
  <style>
    body { padding: 10px 14px; }
    h3 { margin: 0 0 6px; font-size: 13px; }
  </style>
</head>
<body class="bx">
  <h3>%[1]s</h3>
  <script type="module">
    // xbin.self is this component's path; xbin.fetch carries its identity.
    // Call your backend at /api/${xbin.self}/... — see /docs/elements.md.
  </script>
</body>
</html>
`

const goModTpl = `module %s

go 1.24

require github.com/magik6k/xbin/sdk v0.0.0
// Resolved by the workspace go.work (generated by xbind).
`

const goMainTpl = `package main

import (
	"fmt"
	"net/http"

	xbin "github.com/magik6k/xbin/sdk"
)

func main() {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /hello", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "{\"hello\":%q}\n", xbin.Caller(r).From)
	})
	// Guard mutating routes by role:
	// mux.Handle("POST /things", xbin.RoleFunc("writer", createThing))
	xbin.Serve(mux)
}
`

const nodeTpl = `// xbin node backend: listen on the unix socket xbind provides.
const http = require('http');
const sock = process.env.XBIN_SOCKET;

const srv = http.createServer((req, res) => {
  // req.headers['x-xbin-from'] / ['x-xbin-role'] are the verified caller.
  res.setHeader('content-type', 'application/json');
  res.end(JSON.stringify({ hello: req.headers['x-xbin-from'] }) + '\n');
});
srv.listen(sock);
process.on('SIGTERM', () => srv.close(() => process.exit(0)));
`

const pythonTpl = `# xbin python backend: HTTP over the unix socket xbind provides.
import json, os, signal
from http.server import BaseHTTPRequestHandler
from socketserver import UnixStreamServer

class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        # X-XBin-From / X-XBin-Role are the verified caller identity.
        body = json.dumps({"hello": self.headers.get("X-XBin-From")}).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

class Server(UnixStreamServer):
    def get_request(self):
        req, _ = self.socket.accept()
        return req, ("xbin", 0)

srv = Server(os.environ["XBIN_SOCKET"], Handler)
signal.signal(signal.SIGTERM, lambda *_: os._exit(0))
srv.serve_forever()
`

const cgiTpl = `#!/bin/sh
# xbin cgi backend: executed per request; CGI/1.1 env; response on stdout.
# XBIN_FROM / XBIN_ROLE carry the verified caller identity.
echo "Content-Type: application/json"
echo
echo "{\"hello\": \"$XBIN_FROM\", \"path\": \"$PATH_INFO\"}"
`

const apiMDTpl = `# %[1]s API

<!-- The standard xbin API contract (see /docs/elements.md §API contract).
     bx api %[1]s renders this file; the grants UI shows the role table. -->

One-paragraph overview of what %[2]s does and who should call it.

## Roles

| Role   | Grants |
|--------|--------|
| reader | Read %[2]s data |
| writer | Modify %[2]s data |

## Endpoints

### GET /hello — role: any granted

Returns a greeting naming the caller.

` + "```" + `json
{"hello": "apps/other-app"}
` + "```" + `

## Use it

` + "```" + `jsonc
// caller's xbin.json
{ "uses": [{ "target": "%[1]s", "role": "reader" }] }
` + "```" + `
`
