#!/bin/sh
# native/tools/app-stubcheck/run.sh — type-check app files that only Xcode
# can build (SwiftUI, UIKit, WebKit, PhotosUI, SwiftTerm's view) on Linux,
# against stubs: swiftui-stubcheck's SwiftUI/UIKit stubs plus Stubs/ here
# (more UIKit and SwiftUI, WebKit, PhotosUI, UniformTypeIdentifiers,
# SwiftTerm's TerminalView) and stand-ins for the app types those files
# touch (Stubs/AppStubs.swift: WorkspaceModel, WebTileController, …). The
# real XbinCore, XbinTerm and XbinAgent and the renderer's views (as
# swiftui-stubcheck builds them) are linked, so the files are checked
# against the packages as they are, in Swift 6 mode.
#
#   native/tools/app-stubcheck/run.sh [build-dir]
#
# A pass means "consistent with these stubs": it catches our own mistakes
# (a ViewBuilder that assigns, a wrong model API, isolation) before a CI
# round trip; it is NOT a substitute for the Apple CI. FILES lists what it
# covers (the native tile's hatches and the Agent tab); add a file and stub
# what it needs. It first runs swiftui-stubcheck (which builds the renderer).
set -eu
here=$(cd "$(dirname "$0")" && pwd)
repo=$(cd "$here/../../.." && pwd)
out=${1:-${TMPDIR:-/tmp}/xbin-app-stubcheck}
FILES="Tiles/TileAttach.swift Tiles/TileTerminal.swift Tiles/TileCanvas.swift Tiles/TileHatches.swift
Agent/AgentAttachments.swift Agent/AgentChat.swift Agent/AgentScreen.swift"

"$repo/native/tools/swiftui-stubcheck/run.sh" "$out/renderer" >"$out.renderer.log" 2>&1 || {
  cat "$out.renderer.log"; echo 'app-stubcheck: swiftui-stubcheck failed'; exit 1; }

pkg=$out/app
rm -rf "$pkg/Sources"
mkdir -p "$pkg/Sources"
for m in UIKit SwiftUI Charts XbinRendererModel XbinRendererCheck; do cp -R "$out/renderer/Sources/$m" "$pkg/Sources/"; done
# the stubs' UIResponder gets a public init (UIView() in app code)
sed 's/@MainActor open class UIResponder {}/@MainActor open class UIResponder { public init() {} }/' \
  "$out/renderer/Sources/UIKit/UIKit.swift" >"$pkg/Sources/UIKit/UIKit.swift"
cp "$here/Stubs/UIKitExtra.swift" "$pkg/Sources/UIKit/"
cp "$here/Stubs/SwiftUIExtra.swift" "$pkg/Sources/SwiftUI/"
for m in WebKit PhotosUI UniformTypeIdentifiers SwiftTerm; do
  mkdir -p "$pkg/Sources/$m"
  cp "$here/Stubs/$m.swift" "$pkg/Sources/$m/"
done
mkdir -p "$pkg/Sources/App"
cp "$here/Stubs/AppStubs.swift" "$pkg/Sources/App/"
for f in $FILES; do
  # Linux keeps URLSession in FoundationNetworking; the renderer module is
  # XbinRendererCheck here and does not re-export its model.
  { echo "import FoundationNetworking"
    sed -e 's/^import XbinRenderer$/import XbinRendererCheck\
import XbinRendererModel/' "$repo/native/ios/App/$f"; } >"$pkg/Sources/App/$(basename "$f")"
done

cat >"$pkg/Package.swift" <<PKG
// swift-tools-version: 6.2
// Generated by native/tools/app-stubcheck/run.sh — do not edit.
import PackageDescription
let package = Package(
    name: "app-stubcheck",
    platforms: [.macOS(.v26)],
    dependencies: [
        .package(path: "$repo/native/ios/Packages/XbinCore"),
        .package(path: "$repo/native/ios/Packages/XbinTerm"),
        .package(path: "$repo/native/ios/Packages/XbinAgent"),
    ],
    targets: [
        .target(name: "UIKit"),
        .target(name: "UniformTypeIdentifiers"),
        .target(name: "SwiftUI", dependencies: ["UIKit", "UniformTypeIdentifiers"]),
        .target(name: "Charts", dependencies: ["SwiftUI"]),
        .target(name: "WebKit", dependencies: ["UIKit"]),
        .target(name: "PhotosUI", dependencies: ["SwiftUI", "UniformTypeIdentifiers"]),
        .target(name: "SwiftTerm", dependencies: ["UIKit"]),
        .target(name: "XbinRendererModel", dependencies: [.product(name: "XbinCore", package: "XbinCore")]),
        .target(name: "XbinRendererCheck", dependencies: [
            "SwiftUI", "UIKit", "Charts", "XbinRendererModel", .product(name: "XbinCore", package: "XbinCore"),
        ]),
        .target(name: "App", dependencies: [
            "SwiftUI", "UIKit", "WebKit", "PhotosUI", "UniformTypeIdentifiers", "SwiftTerm", "XbinRendererCheck", "XbinRendererModel",
            .product(name: "XbinCore", package: "XbinCore"), .product(name: "XbinTerm", package: "XbinTerm"),
            .product(name: "XbinAgent", package: "XbinAgent"),
        ]),
    ],
    swiftLanguageModes: [.v6]
)
PKG
cd "$pkg" && swift build --target App
