#!/bin/sh
# native/tools/app-stubcheck/run.sh — type-check the app's Model and Shell
# (native/ios/App/Model, App/Shell) on Linux against stubs of the SDK: the
# SwiftUI stubs of native/tools/swiftui-stubcheck plus this tool's
# (Stubs/: a fuller UIKit, WebKit, SafariServices, CoreImage, the SwiftUI the
# shell adds, and the app types those folders use from Tiles/, Terminal/,
# Agent/, Push/). Swift 6 mode, the real XbinCore/XbinTerm/XbinAgent and
# XbinRendererModel. A pass means "consistent with these stubs" (README.md).
#
#   run.sh [--sendable-bindings] [build-dir]
set -eu
here=$(cd "$(dirname "$0")" && pwd)
repo=$(cd "$here/../../.." && pwd)
strict=0
if [ "${1:-}" = "--sendable-bindings" ]; then strict=1; shift; fi
out=${1:-${TMPDIR:-/tmp}/xbin-app-stubcheck}
base=$repo/native/tools/swiftui-stubcheck/Stubs
app=$repo/native/ios/App

mkdir -p "$out/Sources"
rm -rf "$out/Sources/SwiftUI" "$out/Sources/UIKit" "$out/Sources/WebKit" "$out/Sources/SafariServices" \
  "$out/Sources/CoreImage" "$out/Sources/XbinRendererModel" "$out/Sources/AppCheck"
cp -R "$base/SwiftUI" "$out/Sources/"
cp "$here/Stubs/SwiftUI/AppShell.swift" "$out/Sources/SwiftUI/"
# The SDK runs a view's refreshable action on the main actor.
sed -i.orig 's/public func refreshable(action:/public func refreshable(@_inheritActorContext action:/' "$out/Sources/SwiftUI/Modifiers.swift"
if [ "$strict" = 1 ]; then
  sed -i.orig 's/public init(get: @escaping () -> Value, set: @escaping (Value) -> Void)/public init(get: @escaping @Sendable () -> Value, set: @escaping @Sendable (Value) -> Void)/' \
    "$out/Sources/SwiftUI/State.swift"
fi
rm -f "$out/Sources/SwiftUI/"*.orig
for m in UIKit WebKit SafariServices CoreImage; do cp -R "$here/Stubs/$m" "$out/Sources/"; done
cp -R "$repo/native/ios/Packages/XbinRenderer/Sources/XbinRendererModel" "$out/Sources/"
mkdir -p "$out/Sources/AppCheck"
cp "$here/Stubs/App/AppStubs.swift" "$out/Sources/AppCheck/"

# The app's files, each with `import UIKit` first (the stub re-exports
# FoundationNetworking, which URLSession needs on Linux); Objective-C
# selectors become stub values (no ObjC runtime here). Stubbed instead:
# AppTransport and DeviceKeys (URLSession delegates, the Secure Enclave) and
# AddWorkspaceView (VisionKit, AuthenticationServices).
for f in "$app"/Model/*.swift "$app"/Shell/*.swift; do
  case "$(basename "$f")" in AppTransport.swift|DeviceKeys.swift|AddWorkspaceView.swift) continue ;; esac
  { echo "import UIKit"
    sed -E -e '/^import CoreImage\.CIFilterBuiltins$/d' \
      -e 's/#selector\(([^()]*(\([^()]*\))?)\)/Selector("\1")/g' -e 's/@objc //' "$f"
  } >"$out/Sources/AppCheck/$(basename "$f")"
done

cat >"$out/Package.swift" <<PKG
// swift-tools-version: 6.2
// Generated by native/tools/app-stubcheck/run.sh — do not edit.
import PackageDescription
let package = Package(
    name: "app-stubcheck",
    platforms: [.macOS(.v26)],
    dependencies: [
        .package(path: "$repo/native/ios/Packages/XbinCore"),
        .package(path: "$repo/native/ios/Packages/XbinTerm"),
        .package(path: "$repo/native/ios/Packages/XbinAgent"),
    ],
    targets: [
        .target(name: "UIKit"),
        .target(name: "SwiftUI", dependencies: ["UIKit"]),
        .target(name: "WebKit", dependencies: ["UIKit"]),
        .target(name: "SafariServices", dependencies: ["UIKit"]),
        .target(name: "CoreImage", dependencies: ["UIKit"]),
        .target(name: "XbinRendererModel", dependencies: [.product(name: "XbinCore", package: "XbinCore")]),
        .target(name: "AppCheck", dependencies: [
            "UIKit", "SwiftUI", "WebKit", "SafariServices", "CoreImage", "XbinRendererModel",
            .product(name: "XbinCore", package: "XbinCore"),
            .product(name: "XbinTerm", package: "XbinTerm"),
            .product(name: "XbinAgent", package: "XbinAgent"),
        ]),
    ],
    swiftLanguageModes: [.v6]
)
PKG
cd "$out" && swift build
